### PR TITLE
 [JBWS-4178]:clean up logging dependency in jbossws-client

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Comment by jbliznak** [comment]
@jimma what is the purpose of the changes here? From the jira it looked like you wanted to get rid of log4j and slf4j-log4j bridge. In addition to that you are removing slf4j-api and also the dependency management for it. So jbossws-cxf is now relying on jboss-logging?

There is still reference to log4j in jbossws-cxf-jaspi pom.xml.

Also slf4j-api is still brough in by transitive deps:
```
+- org.apache.cxf:cxf-rt-features-logging:jar:3.3.3-SNAPSHOT:compile
|  +- org.apache.cxf:cxf-core:jar:3.3.3-SNAPSHOT:compile
|  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.4:compile
|  \- org.slf4j:slf4j-api:jar:1.7.26:compile
```

**Comment by jimma** [comment]
@jbliznak  Thanks for review and remind me this sl4j dependency. It looks cxf still have to use sl4j for logging feature and it can't be removed. 
But I started a cxf-dev thread to know more details why it need this.  It should be optimized to use CXF's common logger to implement logging feature.

**Comment by jbliznak** [comment]
Maybe also extend enforcer for banned dependencies to be sure it won't come back by transitive deps in the future.
https://github.com/jbossws/jbossws-cxf/blob/master/modules/jaspi/pom.xml#L106
https://github.com/jbossws/jbossws-cxf/blob/master/modules/client/pom.xml#L304
https://github.com/jbossws/jbossws-cxf/blob/master/modules/server/pom.xml#L292

Also if we don't want slf4j do we need it in modules definitions?
https://github.com/jbossws/jbossws-cxf/search?l=XML&q=%22org.slf4j%22

BTW how does it suppose to work when log4j is removed and jbossws-cxf's CXF code is set to use it https://github.com/jbossws/jbossws-cxf/blob/master/modules/client/src/main/resources/META-INF/cxf/org.apache.cxf.Logger ? (see https://cxf.apache.org/docs/general-cxf-logging.html)

**Comment by jimma** [comment]
> Also if we don't want slf4j do we need it in modules definitions?
https://github.com/jbossws/jbossws-cxf/search?l=XML&q=%22org.slf4j%22

@jbliznak  Looks sl44j can't be removed until we find a solution to fix logging MDC in CXF's LoggingUtils.

> BTW how does it suppose to work when log4j is removed and jbossws-cxf's CXF code is set to use it https://github.com/jbossws/jbossws-cxf/blob/master/modules/client/src/main/resources/META-INF/cxf/org.apache.cxf.Logger ? (see https://cxf.apache.org/docs/general-cxf-logging.html)

Looks this should be removed too and let jbossws cxf client use java util logging. I'll look at this more carefully to see how much this change will effect.

**Pull request closed without merging**
