### PR TITLE
[JBEAP-23416] Username Token Profile support with Elytron

### PR DESCRIPTION
**Pull request by Skyllarr**
https://issues.redhat.com/browse/JBEAP-23416

### CODE REVIEW

**Review by asoldano — COMMENTED** [review]
Thanks @Skyllarr for the contribution. @jimma , @rsearls please review.
As a general comment, I can say that once the functionality here is verified to work, we need better isolation between jbossws-cxf and wildfly; classes in jbossws-cxf are not meant to directly access wildfly apis, while they should rely on jbossws-api and jbossws-spi interfaces. The implementation of those interfaces, making use of wildfly classes, is expected to live in the webservices subsystem / ASIL components.

**Comment by rsearls** [comment]
@asoldano There is still one issue that needs to be resolved before I approve this PR.  I have talked to Diana about it.  I will be working on that today and until it is resolved.

**Comment by rsearls** [comment]
Yes, I am working on a new PR to replace this one.  Once all testsuite issues are resolved I will provide it and close this one.

**Comment by rsearls** [comment]
This PR is obsolete.  It has been replaced by https://github.com/jbossws/jbossws-cxf/pull/228/

**Pull request closed without merging**
