### PR TITLE
[JBWS-4151] Review dependency management

### PR DESCRIPTION
**Pull request by jbliznak**
https://issues.jboss.org/browse/JBWS-4151

Dependency management in root pom.xml contains many exclusions yet some of them are no longer needed. This PR tries to update the set of needed exclusions. This is done mostly by removing exclusions not needed anymore but there were also situations where managed dependency with exclusions in dependencyManagement is declared with different/additional set of exclusions in child pom.

### CODE REVIEW

**Comment by jbliznak** [comment]
For easier visual check what has changed with my changes please look at https://github.com/jbliznak/jbossws-cxf/commit/ed7960281a9c2e7abfb88b65912759777b88abbd

**Comment by jbliznak** [comment]
@asoldano  do not merge this yet, it appears the dependency tress are different when executed on JDK8 and JDK11, I must review this next week.

**Comment by asoldano** [comment]
@jbliznak Can I merge this now?

**Comment by jbliznak** [comment]
Please wait a little bit longer, I wasn't able to find time for the review yet. I will announce it here when ready.

**Comment by jbliznak** [comment]
@asoldano this is now ready to merge, changes in dependency trees can be checked at:
https://github.com/jbliznak/jbws-dependency-trees/compare/jdk8-before..jdk8-after
https://github.com/jbliznak/jbws-dependency-trees/compare/jdk11-before..jdk11-after
https://github.com/jbliznak/jbws-dependency-trees/compare/jdk8-before..jdk11-before
https://github.com/jbliznak/jbws-dependency-trees/compare/jdk8-after..jdk11-after

**Pull request merged**
