### PR TITLE
[JBWS-4102] Get rid of some warnings during build

### PR DESCRIPTION
**Pull request by jbliznak**
https://issues.jboss.org/browse/JBWS-4102

This PR covers cases 4 and 5 from the issue

### CODE REVIEW

**Comment by asoldano** [comment]
@jbliznak thanks for the PR. I tried a 'mvn -Pwildfly1100,fast,hudson integration-test' run and I got this at the end of the shared-testsuite:

`[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.231 s - in org.jboss.test.ws.saaj.jbws3857.MultipartContentTypeTestCase
[INFO] Running org.jboss.test.ws.jaxws.jbws2978.JBWS2978TestCase
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.jboss.test.ws.jaxws.jbws2978.JBWS2978TestCase
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 427, Failures: 0, Errors: 0, Skipped: 7
[INFO] 
[ERROR] There are test failures.

Please refer to /dati/jbossws-cxf/modules/testsuite/shared-tests/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
There was an error in the forked process
Cannot remove a null listener
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
Cannot remove a null listener
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (forked-integration-tests) @ jbossws-cxf-shared-tests ---`

WDYT?

**Comment by jbliznak** [comment]
@asoldano I was not able to reproduce with several runs. Were you able to dig any info from /dati/jbossws-cxf/modules/testsuite/shared-tests/target/surefire-reports?

**Comment by jbliznak** [comment]
@asoldano I tried tens of runs, unable to reproduce. Just two notes:
1) the command for fast profile should be 'mvn -Pwildfly1100,fast,hudson post-integration-test' to trigger servers shutdown
2) in fast profile the test run order is set to 'balanced' so the actual tests order may differ signifficantly for our runs

**Comment by asoldano** [comment]
@jbliznak eventually I restarted my machine and the problem went away... no idea what it was. Yes, I post-integration-test is way better than integration-test when enabling the fast profile.
I'm merging this, thanks.

**Pull request merged**
